# Generated by Django 4.0.5 on 2022-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobYouToor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
