# Generated by Django 4.0.5 on 2022-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobyoutoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobyoutoor',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
