# Generated by Django 4.0.5 on 2022-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_employeer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
                ('date_apply', models.DateTimeField(null=True)),
            ],
        ),
    ]
