# Generated by Django 4.0.5 on 2022-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_bewerbungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerbungen',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
